"""Builds SpiderPhish.py - the whole toolkit in ONE
standalone Python file (no project folder needed, only pip requirements).

Usage:
    python scripts/build_singlefile.py

Run the result anywhere:
    python "SpiderPhish.py"
"""
from __future__ import annotations

import base64
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
APP = ROOT / "app"
OUT = ROOT / "SpiderPhish.py"


def module_name(p: Path) -> str:
    rel = p.relative_to(APP.parent)          # e.g. app/gui/theme.py
    parts = list(rel.with_suffix("").parts)
    if parts[-1] == "__init__":
        parts = parts[:-1]
    return ".".join(parts)


def collect() -> tuple[dict[str, str], list[str]]:
    modules: dict[str, str] = {}
    pkgs: list[str] = []
    for p in sorted(APP.rglob("*.py")):
        name = module_name(p)
        modules[name] = p.read_text(encoding="utf-8-sig").lstrip("\ufeff")
        if p.name == "__init__.py":
            pkgs.append(name)
    return modules, pkgs


TEMPLATE = '''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# ============================================================
#  SpiderPhish v1.1.0 - SINGLE-FILE edition
#  ANTI-PHISHING ANALYZER | DEFEND TODAY, HACK TOMORROW
#
#  Run:      python "SpiderPhish.py"
#  Requires: pip install PySide6 httpx pydantic pydantic-settings dnspython
#                  beautifulsoup4 lxml tldextract reportlab cryptography
#                  python-dotenv
#
#  This file embeds the full application source (compressed).
#  Generated by scripts/build_singlefile.py - DO NOT EDIT.
# ============================================================
import sys, os, zlib, base64, ast
import importlib.abc, importlib.machinery

_B64 = "{blob}"

_PAYLOAD = ast.literal_eval(
    zlib.decompress(base64.b64decode(_B64)).decode("utf-8"))
_MODULES: dict = _PAYLOAD["modules"]
_PKGS: set = set(_PAYLOAD["pkgs"])

_IMPLICIT_PKGS: set = set()
for _name in _MODULES:
    _parts = _name.split(".")
    for _i in range(1, len(_parts)):
        _prefix = ".".join(_parts[:_i])
        if _prefix not in _MODULES:
            _IMPLICIT_PKGS.add(_prefix)

BASE_DIR = os.path.dirname(os.path.abspath(__file__))


def _mod_file(name: str) -> str:
    parts = name.split(".")
    if name in _PKGS:
        return os.path.join(BASE_DIR, *parts, "__init__.py")
    return os.path.join(BASE_DIR, *parts) + ".py"


class _EmbedLoader(importlib.abc.Loader):
    def create_module(self, spec):
        return None  # default module creation

    def exec_module(self, module):
        module.__file__ = _mod_file(module.__name__)
        module.__package__ = (module.__name__ if module.__name__ in _PKGS
                              else module.__name__.rpartition(".")[0])
        code = compile(_MODULES[module.__name__], module.__file__, "exec")
        exec(code, module.__dict__)

    def get_source(self, fullname):
        return _MODULES.get(fullname, "")


class _NsLoader(importlib.abc.Loader):
    """Loader for namespace packages (folders without __init__.py)."""

    def create_module(self, spec):
        return None

    def exec_module(self, module):
        module.__path__ = []
        module.__package__ = module.__name__
        module.__file__ = None


class _EmbedFinder(importlib.abc.MetaPathFinder):
    def find_spec(self, fullname, path=None, target=None):
        if fullname in _IMPLICIT_PKGS:
            return importlib.machinery.ModuleSpec(
                fullname, _NsLoader(), is_package=True)
        if fullname not in _MODULES:
            return None
        return importlib.machinery.ModuleSpec(
            fullname, _EmbedLoader(),
            is_package=fullname in _PKGS)


def main() -> int:
    sys.meta_path.insert(0, _EmbedFinder())
    if "--smoke" in sys.argv:
        os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
        from PySide6.QtCore import QTimer
        from PySide6.QtWidgets import QApplication
        from app.gui.context import build_context
        from app.gui.main_window import MainWindow
        from app.gui.theme import build_qss
        app = QApplication(sys.argv)
        app.setStyle("Fusion")
        app.setStyleSheet(build_qss())
        ctx = build_context()
        win = MainWindow(ctx)
        win.show()
        results = {{"ok": True}}
        def finish():
            try:
                raw = open(os.path.join(BASE_DIR, "tests", "data",
                                        "phishing.eml"), "rb").read() \\
                    if os.path.exists(os.path.join(BASE_DIR, "tests")) else None
                print("[SMOKE] window OK; pages:", len(win._pages))
            finally:
                app.quit()
        QTimer.singleShot(2500, finish)
        return app.exec()
    import app.main
    return app.main.run_app()


if __name__ == "__main__":
    raise SystemExit(main())
'''


def main() -> int:
    modules, pkgs = collect()
    print(f"Modules embedded: {len(modules)} "
          f"({sum(len(v) for v in modules.values()):,} bytes source)")
    payload = {"modules": modules, "pkgs": pkgs}
    blob = base64.b64encode(
        zlib.compress(repr(payload).encode("utf-8"), 9)).decode("ascii")
    out = TEMPLATE.format(blob=blob)
    OUT.write_text(out, encoding="utf-8")
    print(f"Written: {OUT} ({OUT.stat().st_size / 1024:.1f} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
